version: '3'

services:
  frontend:
    build: frontend
    restart: 'unless-stopped'
    ports:
      - '80:80'
    networks:
      - hubble-food
  receiver:
    build: receiver
    restart: 'unless-stopped'
    networks:
      - hubble-food

networks:
  hubble-food:
    driver: bridge
