name: Semantic Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  versioning:
    uses: GEWIS/actions/.github/workflows/versioning.yml@v1

  release:
    uses: GEWIS/actions/.github/workflows/docker-release.yml@v1
    needs: versioning
    if: ${{ needs.versioning.outputs.next-version != '' }}
    with:
      projects: "['frontend', 'receiver']"
      version: ${{ needs.versioning.outputs.next-version }}
      docker-paths: "['x/orderlist']"
      github-registry: "true"
    secrets:
      REGISTRY_USERNAME: ${{ secrets.SVC_GH_ABCNC_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.SVC_GH_ABCNC_PWD }}
